# Font and Size
sub-font="JetBrains Mono"
sub-font-size=60               # Size of the subtitle text

# Style settings (Android-like: yellow text, full black square background; keep font & size)
sub-color="#ffff00"             # Yellow text (keeps your font & size)
sub-back-color="#99000000"
sub-border-style=background-box
sub-border-size=0
sub-shadow-offset=0
sub-line-spacing=-35
sub-ass-override=force
save-position-on-quit=no
osc=yes
hwdec=auto
osd-font="Ubuntu"
osd-font-size=28
