-- Exact first-class profile for the current laptop.
-- Display: eDP-1, 2560x1600 at 165 Hz, Hyprland scale 2.

local home = os.getenv("HOME") or "~"

return {
    name = "zayed-laptop",
    monitor = {
        output = "eDP-1",
        mode = "2560x1600@165",
        position = "0x0",
        scale = 2,
    },
    workspace = {
        monitor = "eDP-1",
        first = 1,
        last = 5,
    },
    network_interface = "wlp3s0",
    gpu_driver = "nvidia",
    mangohud_gpu_list = "0",
    qt_scale_factor = "2",
    env = {
        XCURSOR_THEME = "Bibata-Modern-Amber",
        XCURSOR_SIZE = "24",
        HYPRCURSOR_THEME = "Bibata-Modern-Amber",
        HYPRCURSOR_SIZE = "24",
        GDK_BACKEND = "wayland,x11,*",
        QT_QPA_PLATFORM = "wayland;xcb",
        CLUTTER_BACKEND = "wayland",
        XDG_CURRENT_DESKTOP = "Hyprland",
        XDG_SESSION_TYPE = "wayland",
        XDG_SESSION_DESKTOP = "Hyprland",
        QT_AUTO_SCREEN_SCALE_FACTOR = "0",
        QT_ENABLE_HIGHDPI_SCALING = "0",
        QT_QPA_PLATFORMTHEME = "qt6ct",
        QT_WAYLAND_DISABLE_WINDOWDECORATION = "1",
        QT_NO_XDG_DESKTOP_PORTAL = "1",
        GTK_THEME = "gruvbox-dark-gtk",
        GDK_SCALE = "2",
        XFT_DPI = "192",
        LIBVA_DRIVER_NAME = "nvidia",
        GBM_BACKEND = "nvidia-drm",
        __GLX_VENDOR_LIBRARY_NAME = "nvidia",
        NVD_BACKEND = "direct",
        WLR_DRM_NO_ATOMIC = "1",
        STEAM_FORCE_DESKTOPUI_SCALING = "2.0",
    },
    xwayland = {
        force_zero_scaling = true,
    },
    commands = {
        terminal = "kitty",
        file_manager = "thunar",
        menu = "rofi -show drun",
        browser = "brave-browser-stable",
        hyprlock = home .. "/.config/hypr/scripts/hyprlock.sh",
        osd = home .. "/.config/hypr/scripts/osd.sh",
        waybar_launcher = home .. "/.config/waybar/launch.sh",
        waybar_top_config = home .. "/.config/waybar/config-top.jsonc",
        media_daemon = home .. "/.config/waybar/scripts/media-daemon.sh",
        pipewire_launcher = "gentoo-pipewire-launcher",
        wallpaper_daemon = "awww-daemon",
        wallpaper = home .. "/.config/hypr/scripts/wallpaper.sh",
        bluetooth_applet = "blueman-applet",
        tailscale_systray = "tailscale systray",
        polkit_agent = "/usr/libexec/hyprpolkitagent",
        polkit_probe = "test -x /usr/libexec/hyprpolkitagent",
    },
}
